### ISSUE TITLE
PV2 links generated with user-agent working on vlc but not kodi

### ISSUE THREAD

**Issue by ykhehra1** [Shani-08/ShaniXBMCWork2#12]
Hi Shani,

PV2 is still not working for me after latest update.
I added new user agent on getPV2Auth(), even its still not working on kodi but the link from log working fine in VLC.

PS. with  user agent on getPV2Auth() the link generated is longer.

**Comment by saqebakhter** [comment]
What did you change the user agent too for getPV2Auth

**Comment by Shani-08** [comment]
its already updated in 4,0.9 and working
