### ISSUE TITLE
Cannot watch anything in Kodi 16 RC 2

### ISSUE THREAD

**Issue by Shinoby1992** [Shani-08/ShaniXBMCWork2#16]
I got the same playlist working on Kodi 15.2 with lifestreamspro 
but i updated now to Kodi 16 RC 2 and i also deleted livestreamspro installed it new from fresh...still when i start the video, it just load 1 picture and freezes 
its not the server.

http://img4host.net/upload/0122125556afca574b8b1.png

**Comment by Shani-08** [comment]
Sorry, kodi 16 not tested nor supported at this moment. Wait for it to be released.
