### ISSUE TITLE
indian channnels issue

### ISSUE THREAD

**Issue by bhonpo** [Shani-08/ShaniXBMCWork2#20]
hi.. yp indian channels list 80% not working... and ipbox all channels is working but only for few seocnds then gets stoppd automatically..
kindly fix .. many thankss 

ANYWAYS GR88 WORK

 CHEERZ

**Comment by Shani-08** [comment]
ipbox was there with the caution that it will stop working. Now its been removed. yp channels  are not available in your area. In newer version it will check and filter the channels
