### ISSUE TITLE
plugin.video.f4mTester add logo channel

### ISSUE THREAD

**Issue by andykimpe** [Shani-08/ShaniXBMCWork2#24]
plugin.video.f4mTester how under plugin.video.f4mTester for the chanel logo is displayed at the bottom right has the edroit which is provided to this effect?

how with thumbnail fonction

plugin://plugin.video.f4mTester/?streamtype=HLS&amp;name=chanel&amp;thumbnail=http://url/icon.png&amp;url=$doregex[encodedurl]

I wish we could see the logo like this but with f4mtester

display the logo of the chanel lower left

http://img15.hostingpics.net/pics/470046Sanstitre.png

**Comment by andykimpe** [comment]
it would be possible to have an reply please thank you

**Comment by Shani-08** [comment]
the logo is not supported yet

**Comment by andykimpe** [comment]
it would be possible to add in this case please

I do not like when there was not the channel logo

**Comment by Shani-08** [comment]
Its available in the latest version 2.2.5, the parameter is iconImage
