### ISSUE TITLE
Enable parental control

### ISSUE THREAD

**Issue by nicoserafino** [Shani-08/ShaniXBMCWork2#25]
Hi,
I would like to enable parental control and lock a couple of channels, but I didn't found any good addon for that.
My .xml connects to internet, so I can't add <parentalblock>true</parentalblock>. So I'm looking for an addon that can lock menu entries or url streaming

**Comment by Shani-08** [comment]
In LSPro you can hide some enteries if you have <parentalblock>true</parentalblock>
in the settings you would need to enter the pin and enable block, after this the enteries will be hidden.
when you right click anywhere and select unlblock parental block, it will ask for pin and show the items, till you lock it again.
