### ISSUE TITLE
zeemarathi link is wrong 

### ISSUE THREAD

**Issue by send2shishir** [Shani-08/ShaniXBMCWork2#26]
in file plugin.video.serialzone/default.py on line 83 , spelling of "marathi" is spelled wrong as "marathi"
it is  
85 addDir('Marathi' ,'http://marati.serialzone.in/', 2, '')
it should be following 
85 addDir('Marathi' ,'http://marathi.serialzone.in/', 2, '')

Also zee marathi stopped working , I guess its because of latest dittoTV update, not sure though .

**Comment by gowtham20** [comment]
@Shani-08  hello friend, respect your effort, none of kannada serials are working please help by fixing when you have time ( more helpful for house wife to engage ;) )....

**Comment by Shani-08** [comment]
Fixed in ver 1.7 also the url is fixed too
