### ISSUE TITLE
kodi hangs when click indian tv channels

### ISSUE THREAD

**Issue by divnash** [Shani-08/ShaniXBMCWork2#27]
Hi, 
This applies to 1st time install on zemtv 4.9.6. When clicked on indian tv channels, it  hangs kodi at "loading ipbox channels", and when ipbox channels are disabled in settings, no channels show up in indian tv channels category.

**Comment by divnash** [comment]
would be nice to have a timeout for when channels load, otherwise it just stuck till kodi restart. thanks.

**Comment by divnash** [comment]
updte: channels show up with vpn, but kodi hanging issue remains.

**Comment by Shani-08** [comment]
The timeout is there its not always supported. Please disable iptv channels if it still giving you problems
