### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dutchtv** [Shani-08/ShaniXBMCWork2#29]
help me I want to make an addon for Dutch IPTV can you help me?

**Comment by Shani-08** [comment]
what help you want?

**Comment by dutchtv** [comment]
how do I make addon for Dutch and German IPTV

**Comment by Shani-08** [comment]
what do you have? m3u8 file? or just want to scrap the sites?

**Comment by dutchtv** [comment]
m3u8 file

**Comment by Shani-08** [comment]
So you can either use LiveStreamPro addon and use the m3u8 url to play
or Fork the addon and change the line of code to use the m3u8 file as default.

**Comment by dutchtv** [comment]
I would like an addon  as tvsupertuga

**Comment by Shani-08** [comment]
well, he is copied/fork my LiveStreamPro addon, so you can do the same, just copy his addon, change names etc and the url in SOURCES variable, look into default.py file.
