### ISSUE TITLE
Question Adding Captcha Solving?

### ISSUE THREAD

**Issue by Shinoby1992** [Shani-08/ShaniXBMCWork2#3]
Hey, thank you for your add-on "LiveStreams Pro" its awesome...now my website where i watched german live tv has changed it site and asks for a captcha
my regex method don't work anymore now....

can you somehow integrate a captcha work around btw if there is already one would you help me?

**Comment by Shani-08** [comment]
its already part of LSPro, please see this https://forums.tvaddons.ag/shanis-addon-repository/24190-release-livestreamspro-post320388.html#post320388
