### ISSUE TITLE
ARY Digital UK version stopped playing

### ISSUE THREAD

**Issue by uzairjawed** [Shani-08/ShaniXBMCWork2#30]
Hi Shani,

Thanks for the nice plugin, it helped me alot. UK version of ary digital CF has been stopped playing since morning. Is it possible to fix that in your new version?

I have 5.1.0 installed

**Comment by uzairjawed** [comment]
any update on this bro?

**Comment by Shani-08** [comment]
well, because its not free anymore, try another source like ary digital (website) or v3

**Comment by uzairjawed** [comment]
yeah tried it but they all are from Ary Digital Pakistan.

**Comment by Shani-08** [comment]
try 5.1.5 can't promise it will last any longer! so enjoy till it lasts
