### ISSUE TITLE
“more options here to control the f4m Proxy, please any key to close”

### ISSUE THREAD

**Issue by limelect** [Shani-08/ShaniXBMCWork2#36]
Urgent we cannot use kody!!!! 
Plz fix this problem 
“more options here to control the f4m Proxy, please any key to close”
https://forums.tvaddons.ag/vpn-and-proxy-discussion/52331-options-control-f4m-proxy-please-key-close.html#post387164

**Comment by limelect** [comment]
If fixed the problem
https://forums.tvaddons.ag/shanis-addon-repository/21751-release-f4m-hds-streamer-xmbc-43.html?posted=1#post387760

But shani has to fix the source

**Comment by Shani-08** [comment]
Nothing to fixed as its already fixed follow the thread to see the resolution.

**Comment by limelect** [comment]
"Nothing to fixed as its already fixed follow the thread to see the resolution."
can you explain or put a link for  resolution

**Comment by Shani-08** [comment]
first check this https://forums.tvaddons.ag/shanis-addon-repository/21751-release-f4m-hds-streamer-xmbc-post387932.html#post387932 i replied you back

secondly, https://github.com/Shani-08/ShaniXBMCWork2/blob/master/script.video.F4mProxy/addon.py is the code for F4mProxy, so if you going to launch (Or some other addon launch it) at the time of kodi load then you will see that message. None of my addon runs at the Kodi startup nor they are service so something else is going on.

**Comment by limelect** [comment]
Shani sorry to say you do not understand the nature of the problem.
Your message is shown not at kodi  start up but at random ALL THE TIME!!
Once i took  off ZEM the problem stoped.
ZEM is a trigger to your software.!!!!
See my link https://forums.tvaddons.ag/shanis-addon-repository/21751-release-f4m-hds-streamer-xmbc-43.html?posted=1#post387760
for the problem on the log !!!!!!!!!

**Comment by Shani-08** [comment]
Zem doesn't load anything on its own unless you click on Zem, Its not a service, The link you posted was was the repo Issue which has been resolved and you need to delete the addons db file to resolve it or follow this https://forums.tvaddons.ag/shanis-addon-repository/52609-cant-instal-zem-post388577.html#post388577

**Comment by limelect** [comment]
Taking out ZEM solved your message. period. 
As for that i give up.
P.S see my site www.limelect.com
for my credentials .

**Comment by Shani-08** [comment]
Not doubting you. Just saying that zem was trying to update itself and was using f4mproxy as repo. All these issue been fixed and if you still had the issue, just deleting the addon db would have fixed. Hence no more code changes required.
