### ISSUE TITLE
LiveStreamsPro + fm4Tester: choppy playback in Kodi v17.0 "Krypton" beta6

### ISSUE THREAD

**Issue by JayBrown** [Shani-08/ShaniXBMCWork2#38]
LiveStreamsPro and fm4Tester/Proxy used to run smoothly with Kodi v16; in the current v17 beta there is choppy playback, video pauses while the engine is "seeking", buffering dropouts etc.

**Comment by alibbaba** [comment]
This is kind of expected as in V17 they are rewriting the Kodi Videoplayer. I had the similar problem where f4mproxy will hang but after updating to  nightly V17 things got improved. So, i will suggest to try nightly.
