### ISSUE TITLE
Fm4tester stuck on 0℅

### ISSUE THREAD

**Issue by ghost** [Shani-08/ShaniXBMCWork2#39]
I installed the repo of this and I go to get addons  > shanis repos > video addons and zem says update available but dosent update and f4mtester stuck on 0℅ am using openelec on my laptop

**Comment by Shani-08** [comment]
follow this
https://forums.tvaddons.ag/shanis-addon-repository/52609-cant-instal-zem.html#post388577

**Comment by lolbob181** [comment]
Thanks its fixed now :)
