### ISSUE TITLE
can't install f4mtester on kodi

### ISSUE THREAD

**Issue by josmulder** [Shani-08/ShaniXBMCWork2#40]
Hi,
I tried to install f4mtester on kodi. I did this by selecting install in the repository. But nothing happens. Then I downloaded the latest zip.file from Github. Selecting install from zip. Then i get a message the the addon isn't installed.
Do you know what is wromg?

Kind regards Jos Mulder.

**Comment by Shani-08** [comment]
follow this
https://forums.tvaddons.ag/shanis-addon-repository/52609-cant-instal-zem.html#post388577
