### ISSUE TITLE
Buffering time

### ISSUE THREAD

**Issue by bfar97** [Shani-08/ShaniXBMCWork2#43]
I'm using f4mtester along with an IPTV addon and was just wondering if there was a way to change the buffering time, since my internet seems a little bit on the low end speed to keep up with the live channels. That way it would be cool if the channel could buffer a little bit more before it started playing

**Comment by Shani-08** [comment]
Please read this but i can tell you that iptv ts urls are very high quality so it will be problem if bandwidth is not there. http://kodi.wiki/view/HOW-TO%3AModify_the_video_cache
