### ISSUE TITLE
LiveStreamsPro - Add plugin parameters

### ISSUE THREAD

**Issue by IvanRF** [Shani-08/ShaniXBMCWork2#44]
I'm trying to play streams with a `Referer` on PVR (IPTV Simple Client).
I found [IPTV Simple Plugin Player](http://repo.thewiz.info/download.php?name=service.iptvsimple.plugin.player) which might be useful ([example](http://forum.kodi.tv/showthread.php?tid=304510)).

I tested it and it worked for:
`http://localhost:62555/?plugin://plugin.video.youtube/play/?video_id=...`

Now, what I need is LiveStreamsPro to support parameters like an `url` and a `referer`. For example:
`http://localhost:62555/?plugin://plugin.video.live.streamspro/?link=...&referer=...`

Could you add this? I saw you already use parameters in the settings for: `plugin://plugin.video.live.streamspro/?mode=...`

**Comment by Shani-08** [comment]
everything you need is already supported, there an example on the forum but its down at the moment.

**Comment by IvanRF** [comment]
@Shani-08 nice 👍 , could you tell me which are the parameters? or post a simple example since it seems they are working on the forum (if you know which thread is, it might be available on Google cache)

**Comment by Shani-08** [comment]
this is the cache url [https://webcache.googleusercontent.com/search?q=cache:J6O9KbIIdaQJ:https://forums.tvaddons.ag/shanis-addon-repository/48441-start-f4m-tester-pvr-iptv-simple.html+&cd=1&hl=en&ct=clnk&gl=uk](url)

and this was the text
For time being there is a way to run the plugin:// urls via Simple Client. You need to install Simple Iptv Plugin Player.
Once installed, create an m3u8 file with your url, for example like this 
First one is direct m3u8 
second and third is a call to Zem (make sure you have Zem installed if you want to play)
Fourth one is LSPro call. you need to pass the item tag, but make sure the item tag is encoded (use http://meyerweb.com/eric/tools/dencoder/). Currently simple IPTV only support 1024 characters for url so for test use smaller item.
62555 is the port number, so if you change it in Plugin Player then use the correct port in m3u8 file.

Code:
```
#EXTM3U
#EXTINF:-1 tvg-id="Test Direct" tvg-name="Test Direct" tvg-logo="direct" group-title="Sports",Direct M3u8
http://stream.gravlab.net/003119/sparse/v1d30/pages/nightskyHLS/Lapse2.m3u8 
#EXTINF:-1 tvg-id="Sky Sport 1" tvg-name="Sky Sport 1" tvg-logo="SSP1" group-title="Sports",Sky Sport 1 Zem
http://localhost:62555/?plugin://plugin.video.ZemTV-shani/?url=MTU3&mode=37&name=test
#EXTINF:-1 tvg-id="Sky Sport 2" tvg-name="Sky Sport 2" tvg-logo="SSP2" group-title="Sports",Sky Sport 2 Zem
http://localhost:62555/?plugin://plugin.video.ZemTV-shani/?url=MTU4&mode=37&name=test
#EXTINF:-1 tvg-id="Call to LSPRO with regex" tvg-name="Call to LSPRO with regex" tvg-logo="SSP2" group-title="Sports",Call to LSPRO with regex
http://localhost:62555/?plugin://plugin.video.live.streamspro/?playitem=%3Citem%3E%0A%3Ctitle%3ETestMe%3C%2Ftitle%3E%0A%3Clink%3E%24doregex%5Bopengate%5Dhttp%3A%2F%2Fcdn.drm.protv.ro%2Fprotvplus.ro%2F2016%2F09%2F20%2F2fb62f445d68e041e369873f5349abb9.ism%2F2fb62f445d68e041e369873f5349abb9-audio%3D255885-video%3D1001000.m3u8%7CCookie%3D%24get_cookies%24%26amp%3BOrigin%3Dhttp%3A%2F%2Fprotvplus.ro%26amp%3BReferer%3Dhttp%3A%2F%2Fprotvplus.ro%2Fprodus%2Fvocea-romaniei%2Fvideo%2F6728-vocea-romaniei-2015-finala%3C%2Flink%3E%3Cregex%3E%0A%3Cname%3Eopengate%3C%2Fname%3E%0A%3Cexpres%3E%3Cexpres%3E%3Cpage%3Ehttp%3A%2F%2Fdrmapi.protv.ro%2Fhlsengine%2Fprepare%2F%3C%2Fpage%3E%3CcookieJar%3E%3C%2FcookieJar%3E%3Creferer%3Ehttp%3A%2F%2Fprotvplus.ro%2Fprodus%2Fvocea-romaniei%2Fvideo%2F6728-vocea-romaniei-2015-inala%3C%2Freferer%3E%0A%3Cagent%3EMozilla%2F5.0%20(Windows%20NT%2010.0%3B%20WOW64)%20KHTML%2C%20like%20Gecko)%20Chrome%2F47.0.2526.80%20Safari%2F537.36%3C%2Fagent%3E%3C%2Fregex%3E%3C%2Fitem%3E
```
Moving forward, i will bring the webserver inside the LSPro so that when you access first time, it will return the m3u8 and in the simple iptv client we would only need to add a url etc. but thats for future.

**Comment by IvanRF** [comment]
Thanks! so the parameter I was looking for is `playitem` 👍 

I did a test with my current code and it throws an error:
```
<item>
<title>Test</title>
<link>http://domain.com/Playlist.m3u8|Referer=http://anotherdomain.com</link>
</item>
```

I decoded your example, changed the URLs and my channel finally works on PVR! thanks!
Anyway, do you know why the previous <link> works on LSPro but not when used on `playitem`?

**Comment by IvanRF** [comment]
This is the error:
```
21:50:11 T:5744  NOTICE: Creating InputStream
21:50:11 T:12460   ERROR: 127.0.0.1 - - [08/Feb/2017 21:50:11] code 501, message Unsupported method ('HEAD')
21:50:11 T:12460   ERROR: 127.0.0.1 - - [08/Feb/2017 21:50:11] "HEAD /?plugin://plugin.video.live.streamspro/?playitem=.... HTTP/1.1" 501 -
21:50:11 T:12460   ERROR: 127.0.0.1 - - [08/Feb/2017 21:50:11] "GET /?plugin://plugin.video.live.streamspro/?playitem=... HTTP/1.1" 200 -
21:50:12 T:12460   ERROR: 127.0.0.1 - - [08/Feb/2017 21:50:12] "GET /?plugin://plugin.video.live.streamspro/?playitem=... HTTP/1.1" 200 -
21:50:12 T:3256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "...Kodi\addons\plugin.video.live.streamspro\default.py", line 3127, in <module>
                                                url,setresolved = getRegexParsed(regexs, url)
                                              File "...Kodi\addons\plugin.video.live.streamspro\default.py", line 971, in getRegexParsed
                                                regexs = eval(urllib.unquote(regexs))
                                              File "...Kodi\system\python\Lib\urllib.py", line 1223, in unquote
                                                bits = s.split('%')
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--
```

**Comment by IvanRF** [comment]
Is `<thumbnail>` suppose to work with `playitem`? I can see that `<title>` works, but not the channel image when the stream is opened.

**Comment by IvanRF** [comment]
@Shani-08 I think you could add the same option that you have on ZemTV to LSPro.
In ZemTV you point to an already existing URL and a name:
`plugin://plugin.video.ZemTV-shani/?url=MTU4&mode=37&name=test`

In LSPro you could add parameters to match a `source` title and a `channel` title (I don't know if there is another way to identify a channel in an xml list). For example:
`plugin://plugin.video.live.streamspro/?source=MyList&channel=MyChannel`

Then you just get the code from the source file and there is no need to Encode/Decode all the `<item>` content.

**Comment by Shani-08** [comment]
can do, but channels names are not unique, regardless, i am planning to have a option in LSPro which will create the m3u8 file for you. just little busy these days. will see if there is a need for this as well.
