### ISSUE TITLE
[Krypton] The new Videoplayer ignores headers now

### ISSUE THREAD

**Issue by rscm** [Shani-08/ShaniXBMCWork2#46]
Hi
I just found out this... is not in the changelog
`http://kodi.wiki/view/Kodi_v17_(Krypton)_changelog`
`http://kodi.wiki/view/DVDPlayer`

and after the upgrade some streams do not play because of this... do you know a way around it? or just a "simple" donwgrade to Jarvis is the only solution atm?

as you can read below, the devs did this on purpose (security reasons)

this is one of the streams (free OTA channel who also streams for free)
`http://d28d7tc1ojykcy.cloudfront.net/lared/smil:lared.smil/playlist.m3u8|User-agent=iPhone&amp;Referer=http://d1e8b5coppv0r9.cloudfront.net`
website
`http://lared.cl/senal-online`

ref:
`https://github.com/xbmc/xbmc/pull/9330`
`http://forum.kodi.tv/showthread.php?tid=280318`

**Comment by alibbaba** [comment]
It semms to work on windows with only user-agent. What is your kodi version? Mine is ```Starting Kodi (17.0 Git:20170201-a10c504). Platform: Windows NT x86 32-bit``` 

Yes http-headers was removed when Krypton was in alpha stage but i remember correctly it has been put back. Thats how i can still play your linked video. Thanks

**Comment by rscm** [comment]
Kodi 17.0 Git:20170201-a10c504
Platform: Windows 10 x64 (10.0.14393.206)

well bad example lol... before it did not work w/o the referer part...now it does with only the user-agent as u said...they changed that (a good thing)

now...actually reading the code part
https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L833
and
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L691

they do pass headers... but i need to test it because if right now if I try a m3u8 link using the browser modifying the header I get the file then all the way to the actual ts video file w/o problems... now with kodi it does not say error 403 but 404... weird right?.. so curl gets the header right and grab the playlist but ffmpeg doesn't so it can't access/play the video.


[using user-agent to check bc is treated different]
curl part
```
04:20:30.642 T:12180  NOTICE: VideoPlayer: Opening: http://url/master.m3u8|X-Forwarded-For=xxxx.xxxx.xxxx.xxxx&User-Agent=iPhone
04:20:30.642 T:12180 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
04:20:30.642 T:12180   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'X-Forwarded-For: xxxx.xxxx.xxxx.xxxx'
04:20:30.838 T:12180   DEBUG: CCurlFile::GetMimeType - http://url/master.m3u8|X-Forwarded-For=xxxx.xxxx.xxxx.xxxx&User-Agent=iPhone -> application/x-mpegURL
04:20:30.838 T:12180   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
04:20:30.838 T:12180   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
04:20:30.839 T:220   DEBUG: Thread VideoPlayer start, auto delete: false
04:20:30.840 T:220  NOTICE: Creating InputStream
04:20:30.840 T:220   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'X-Forwarded-For: xxxx.xxxx.xxxx.xxxx'
04:20:30.840 T:220   DEBUG: CurlFile::Open(0535EF1C) http://url/master.m3u8
```
ffmpeg part
```
04:20:31.393 T:220  NOTICE: Creating Demuxer
04:20:31.393 T:220   DEBUG: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() adding ffmpeg option 'user-agent: iPhone'
04:20:31.393 T:220   DEBUG: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() adding custom header option 'X-Forwarded-For: xxxx.xxxx.xxxx.xxxx'
04:20:33.180 T:220   DEBUG: ffmpeg[DC]: [http] HTTP error 404 Not Found
04:20:33.181 T:220   DEBUG: Error, could not open file http://url/master.m3u8
04:20:33.181 T:220   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
04:20:33.181 T:220  NOTICE: CVideoPlayer::OnExit()
```

probably this...who knows
https://trac.ffmpeg.org/ticket/3268

like i said.. needs more testing

**Comment by Shani-08** [comment]
There was a bug in Kodi for absolute and relative media file as well as not sending the cookies. The solution was to get the master file once via urllib2 then call with Player with url and the cookies of master.
The headers are working in krypton in general so may be very specific tweak you need. You have to post the url or pm if you need more help.
