### ISSUE TITLE
SerialZone proxy

### ISSUE THREAD

**Issue by ykhehra1** [Shani-08/ShaniXBMCWork2#6]
Hi, the proxy in serial zone only applied to get the stream link? or whole video stream through proxy server? If its later case, is it possible that it only fetch the link through proxy and but play the video through local ip (like some smart dns services do)?
Thanks for great work. Its working just sometimes buffers, so wondering.

PS. I noticed proxy only works windows but not Android (nexus player)

**Comment by Shani-08** [comment]
smart dns also uses proxy for geo location as the sources are checking the location at the time of video play so the whole video is being played from proxy. 
There are no free smart dns that you can use reliably.
